# Generated by Django 5.0.7 on 2024-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("logistician", "Логист"), ("partner", "Партнер"), ("", "Не указана")],
                max_length=16,
                verbose_name="Роль",
            ),
        ),
    ]
