repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.9
    hooks:
      - id: typos
