# Generated by Django 5.1.1 on 2024-09-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "Новый заказ"),
                    ("processing", "Обработка"),
                    ("delivery", "Доставка"),
                    ("paid", "Оплачен"),
                    ("returned", "Возвращен"),
                ],
                default="new",
                max_length=16,
                verbose_name="Состояние",
            ),
        ),
    ]
