# Generated by Django 5.1.1 on 2024-09-17 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_alter_order_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="state_changed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата изменения состояния"
            ),
        ),
    ]
