# Generated by Django 5.1 on 2024-08-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                help_text="alpha_2", max_length=16, unique=True, verbose_name="Код"
            ),
        ),
    ]
