# Generated by Django 5.0.7 on 2024-07-30 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
        ("tg_bots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="tg_chat",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner",
                to="tg_bots.tgchat",
                verbose_name="Чат в Telegram",
            ),
        ),
    ]
