# Generated by Django 5.0.7 on 2024-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TgChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("channel", "Канал"),
                            ("private", "Приватный"),
                            ("group", "Группа"),
                            ("supergroup", "Супер-группа"),
                        ],
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "external_id",
                    models.PositiveBigIntegerField(
                        db_index=True, unique=True, verbose_name="TG ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Описание"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="Текстовый идентификатор",
                    ),
                ),
                (
                    "invite_link",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Ссылка - приглашение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат",
                "verbose_name_plural": "Чаты",
            },
        ),
        migrations.CreateModel(
            name="TgUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения"),
                ),
                (
                    "is_bot",
                    models.BooleanField(help_text="Является ли ботом", verbose_name="Бот"),
                ),
                (
                    "external_id",
                    models.PositiveBigIntegerField(
                        db_index=True, unique=True, verbose_name="TG ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        unique=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Фамилия"),
                ),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=16, verbose_name="Язык"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="TgUserChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Связь пользователя с чатом",
                "verbose_name_plural": "Связи пользователей с чатами",
            },
        ),
    ]
