# Generated by Django 5.0.6 on 2024-07-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Дата доставки"
            ),
        ),
    ]
